#Scythe
left-click:
  replant:
    enabled: true
    require-tool: false
right-click:
  harvest:
    enabled: true
    require-tool: false
  replant:
    enabled: true
    require-tool: false
replant:
  require-seeds: false
#Only applies if "require-tool" is true in any of the above categories
tools:
  # Note: In vanilla, harvesting normally crops does NOT use durability
  harvest-uses-durability: false
  prevent-tool-break: true
  minimum-durability: 10
replant-tools:
  - "minecraft:wooden_hoe"
  - "minecraft:stone_hoe"
  - "minecraft:iron_hoe"
  - "minecraft:golden_hoe"
  - "minecraft:diamond_hoe"
  - "minecraft:netherite_hoe"
# Item models should be declared like "namespace:id"
replant-tools-item-models: []
play-sounds: true
sound: BLOCK_CROP_BREAK
sound-volume: 1
sound-pitch: 1
break-particles: true
#Please choose a particle from this list: https://jd.papermc.io/paper/1.20/org/bukkit/Particle.html
particle: CRIT
particle-count: 4
# how far from the center particles should go
particle-spread: 0.5
#crops the plugin should work on
allowed-crops:
  - BEETROOTS
  - CARROTS
  - COCOA
  - NETHER_WART
  - POTATOES
  - WHEAT
