name: Scythe
version: '${project.version}'
main: simplexity.scythe.Scythe
author: RhythmicSystem
website: https://github.com/Simplexity-Development/Scythe
api-version: 1.21.5
permissions:
  scythe.item:
    description: Allows the user to summon a scythe item
    default: op
  scythe.item.others:
    description: Allows the user to send another user a scythe item
    default: op
  scythe.bypass.cooldown:
    description: Allows user to bypass the configured command cooldown
    default: op
  scythe.use:
    description: Allow players to use Scythe Functionality
    default: true
    children:
      scythe.use.harvest: true
      scythe.use.replant: true
      scythe.toggle: true
  scythe.use.harvest:
    description: Allow players to harvest crops using Scythe functionality
    default: true
  scythe.use.replant:
    description: Allow players to replant crops using Scythe functionality
    default: true
  scythe.toggle:
    description: Allow players to toggle Scythe functionality on or off
    default: true
  scythe.reload:
    description: Allows user to reload the Scythe plugin
    default: true
commands:
  scythe:
    description: base command for Scythe plugin
    permission: scythe.use
  scythe-item:
    description: gives the user or provided user a scythe item
    permission: scythe.item
softdepend:
  - CoreProtect

